name: Deploy Hugo Site

on:
  push:
    branches: [main]  # 确保触发分支是 main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 必须启用子模块拉取

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify  # 生成静态文件到 public 目录

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY2 }}  # 密钥名称必须一致
          external_repository: dwh20010724/dwh20010724.github.io  # 替换为你的发布仓库
          publish_branch: main  # 推送目标分支
          publish_dir: ./public  # 发布目录
          user_name: "dwh20010724"
          user_email: "2661490716@qq.com"
          commit_message: 'Automated deployment'
