name: Deploy Hugo Site

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true  # 如果使用Hugo扩展版需要开启

      - name: Check theme
        run: |
          echo "Theme directory contents:"
          ls -la themes/
          git submodule status

      - name: Build
        run: hugo --minify -F --cleanDestinationDir
        env:
          TZ: Asia/Shanghai  # 北京时间时区

      - name: Validate build
        run: |
          ls -la public/posts/  # 确认生成的文章目录存在
          grep -r "h1" public/  # 检查是否包含有效内容

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.Blog Automated Deploy2 }}
          external_repository: dwh20010724/dwh20010724.github.io
          publish_branch: main
          publish_dir: ./public
          user_name: "dwh20010724"
          user_email: "2661490716@qq.com"
          commit_message: 'Automated deployment'
          force_orphan: true  # 强制清理旧文件
